name: Python Check & Format

on: [push, pull_request]

jobs:
  check-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black to format code
        run: |
          black .

      - name: Check code formatting
        run: |
          black --check . 
          echo "Code is formatted correctly."
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "*.py"
          echo "All tests passed successfully."
      - name: Notify on failure
        if: failure()
        run: |
          echo "Some tests failed. Please check the logs for details."
          exit 1
      - name: Notify on success
        if: success()
        run: |
          echo "All checks passed successfully. Code is formatted and tests are passing."
          exit 0
      - name: Commit changes
        if: always() && success()
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "
